### ISSUE TITLE
ModuleNotFoundError: No module named 'nvdb'

### ISSUE THREAD

**Issue by nicokant** [NINAnor/nina-pygeoapi#3]
Following the setup instructions, it results in a error.

```
Traceback (most recent call last):
  File "/app/.venv/bin/pygeoapi", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/pygeoapi/openapi.py", line 1206, in generate
    content = yaml.safe_dump(get_oas(s), default_flow_style=False)
                             ^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/pygeoapi/openapi.py", line 1159, in get_oas
    return get_oas_30(cfg)
           ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/pygeoapi/openapi.py", line 489, in get_oas_30
    p = load_plugin('provider', get_provider_by_type(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/pygeoapi/plugin.py", line 106, in load_plugin
    module = importlib.import_module(packagename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nvdb'

```

**Comment by frafra** [comment]
Fix in 73cb2b62c4c25bdfa88c4e9eb1c81a4bbefe2f6e
